# -*- coding: utf-8 -*-
"""YOLOv5_video.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/19H5U2Uf3VaewdWiJts0d6TDtWca6KSVi
"""

!git clone https://github.com/ultralytics/yolov5

# Commented out IPython magic to ensure Python compatibility.
# %cd yolov5

# Commented out IPython magic to ensure Python compatibility.
# %pip install -qr requirements.txt  # install

import torch
import utils
display = utils.notebook_init()  # checks

from google.colab import drive
drive.mount('/content/drive')

!python detect.py --weights yolov5s.pt --img 640 --conf 0.25 --source /content/video.mp4

#Output File found in the path "/content/yolov5/runs/detect/exp2"